<a href="https://colab.research.google.com/github/sancarhacer/MachineLearning/blob/main/RegressionDecision.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In this section, we are using the LazyPredict library to quickly train and compare multiple regression models on the diabetes dataset.


In [1]:
#https://github.com/shankarpandala/lazypredict
!pip install lazypredict

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 26.7/26.7 MB 77.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.2/2.2 MB 92.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 67.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 147.8/147.8 kB 13.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 329.1/329.1 kB 21.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 114.9/114.9 kB 8.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 85.0/85.0 kB 7.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 86.2/86.2 kB 7.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 718.4/718.4 kB 50.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 203.4/203.4 kB 17.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 106.6/106.6 kB 9.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 96.4/96.4 kB 9.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 72.5/

In [2]:
from lazypredict.Supervised import LazyRegressor
from sklearn import datasets
from sklearn.utils import shuffle
import numpy as np
diabetes  = datasets.load_diabetes()
type(diabetes)

sklearn.utils._bunch.Bunch

In [3]:
diabetes.data

array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
         0.01990749, -0.01764613],
       [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
        -0.06833155, -0.09220405],
       [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
         0.00286131, -0.02593034],
       ...,
       [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
        -0.04688253,  0.01549073],
       [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
         0.04452873, -0.02593034],
       [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
        -0.00422151,  0.00306441]])

In [4]:
diabetes.target

array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
        69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
        68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
        87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
       259.,  53., 190., 142.,  75., 142., 155., 225.,  59., 104., 182.,
       128.,  52.,  37., 170., 170.,  61., 144.,  52., 128.,  71., 163.,
       150.,  97., 160., 178.,  48., 270., 202., 111.,  85.,  42., 170.,
       200., 252., 113., 143.,  51.,  52., 210.,  65., 141.,  55., 134.,
        42., 111.,  98., 164.,  48.,  96.,  90., 162., 150., 279.,  92.,
        83., 128., 102., 302., 198.,  95.,  53., 134., 144., 232.,  81.,
       104.,  59., 246., 297., 258., 229., 275., 281., 179., 200., 200.,
       173., 180.,  84., 121., 161.,  99., 109., 115., 268., 274., 158.,
       107.,  83., 103., 272.,  85., 280., 336., 281., 118., 317., 235.,
        60., 174., 259., 178., 128.,  96., 126., 28

In [5]:
X, y = shuffle(diabetes.data, diabetes.target, random_state=13)
X = X.astype(np.float32)
offset = int(X.shape[0] * 0.9)

X_train, y_train = X[:offset], y[:offset]
X_test, y_test = X[offset:], y[offset:]
y_train

array([272.,  90.,  86., 232., 281.,  88., 235., 151., 152.,  98.,  85.,
       270., 113., 263., 225., 178., 152., 275., 125., 167., 102.,  63.,
        72.,  72., 150., 283.,  87., 200., 179.,  47., 259., 253., 129.,
       258., 132., 161., 178., 154., 144., 179.,  53., 140., 182.,  97.,
       292., 172.,  91.,  48., 116., 185., 170., 129., 104.,  85.,  97.,
        84., 170.,  87., 186., 273., 230., 141., 134.,  96.,  94.,  71.,
       214., 235., 252.,  72., 276., 197.,  91., 277., 145.,  52., 131.,
        91.,  65., 102.,  93., 191.,  83., 201.,  96., 118., 168.,  71.,
       258.,  84., 108., 185., 198., 262.,  78., 172.,  72.,  40., 243.,
        93., 279., 306., 111., 217.,  67., 197., 144.,  42.,  43., 246.,
       113.,  59., 128., 225., 156., 219.,  64., 163.,  99.,  52., 103.,
        90.,  96., 275., 129.,  48., 264.,  77., 182., 212., 268.,  81.,
        85., 242., 121., 195., 293.,  83.,  91., 190., 109., 146., 177.,
       185., 233.,  65., 113., 310.,  74., 139.,  6

In [6]:
reg = LazyRegressor(verbose=0, ignore_warnings=False, custom_metric=None)
models, predictions = reg.fit(X_train, X_test, y_train, y_test)
models

  0%|          | 0/42 [00:00<?, ?it/s]

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000201 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 640
[LightGBM] [Info] Number of data points in the train set: 397, number of used features: 10
[LightGBM] [Info] Start training from score 151.722922
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: 

Adjusted R-Squared  R-Squared   RMSE  \
Model                                                                 
ExtraTreesRegressor                          0.38       0.52  54.22   
OrthogonalMatchingPursuitCV                  0.37       0.52  54.39   
Lasso                                        0.37       0.52  54.46   
LassoLars                                    0.37       0.52  54.46   
LarsCV                                       0.37       0.51  54.54   
LassoCV                                      0.37       0.51  54.59   
PassiveAggressiveRegressor                   0.37       0.51  54.74   
LassoLarsIC                                  0.36       0.51  54.83   
SGDRegressor                                 0.36       0.51  54.85   
RidgeCV                                      0.36       0.51  54.91   
Ridge                                        0.36       0.51  54.91   
BayesianRidge                                0.36       0.51  54.94   
TransformedTargetRegressor                   0.36       0.51  54.96   
LinearRegression                             0.36       0.51  54.96   
LassoLarsCV                                  0.36       0.51  54.96   
Lars                                         0.36       0.50  55.09   
ElasticNetCV                                 0.36       0.50  55.20   
HuberRegressor                               0.36       0.50  55.24   
RandomForestRegressor                        0.35       0.50  55.48   
AdaBoostRegressor                            0.34       0.49  55.88   
LGBMRegressor                                0.34       0.49  55.93   
HistGradientBoostingRegressor                0.34       0.49  56.08   
PoissonRegressor                             0.32       0.48  56.61   
ElasticNet                                   0.30       0.46  57.49   
KNeighborsRegressor                          0.30       0.46  57.57   
OrthogonalMatchingPursuit                    0.29       0.45  57.87   
BaggingRegressor                             0.29       0.45  57.92   
GradientBoostingRegressor                    0.25       0.42  59.70   
TweedieRegressor                             0.24       0.42  59.81   
XGBRegressor                                 0.22       0.40  60.60   
GammaRegressor                               0.22       0.40  60.61   
RANSACRegressor                              0.20       0.38  61.40   
LinearSVR                                    0.12       0.32  64.66   
ExtraTreeRegressor                           0.00       0.23  68.73   
NuSVR                                       -0.07       0.18  71.06   
SVR                                         -0.10       0.15  72.04   
DummyRegressor                              -0.30      -0.00  78.37   
QuantileRegressor                           -0.35      -0.04  79.84   
DecisionTreeRegressor                       -0.47      -0.14  83.42   
GaussianProcessRegressor                    -0.77      -0.37  91.51   
MLPRegressor                                -1.87      -1.22 116.51   
KernelRidge                                 -5.04      -3.67 169.06   

                               Time Taken  
Model                                      
ExtraTreesRegressor                  1.15  
OrthogonalMatchingPursuitCV          0.02  
Lasso                                0.02  
LassoLars                            0.02  
LarsCV                               0.06  
LassoCV                              0.19  
PassiveAggressiveRegressor           0.02  
LassoLarsIC                          0.02  
SGDRegressor                         0.01  
RidgeCV                              0.02  
Ridge                                0.01  
BayesianRidge                        0.11  
TransformedTargetRegressor           0.01  
LinearRegression                     0.02  
LassoLarsCV                          0.04  
Lars                                 0.05  
ElasticNetCV                         0.49  
HuberRegressor                       0.11  
RandomForestRegressor     

The goal of this code is to quickly benchmark multiple regression algorithms on the diabetes dataset without writing separate code for each model. This allows us to identify the best-performing algorithms efficiently.